project:
  type: website
  output-dir: docs

website:
  title: "mywebsite"
  navbar:
    left:
      - href: wuxi.qmd
        text: Wuxi

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

